### ISSUE TITLE
Q: Will other JOIN kind like LEFT JOIN be supported in future?

### ISSUE THREAD

**Issue by leetesla** [facebookincubator/ent#112]
> dialect/sql/builder.go

```
func (s *Selector) Join(t TableView) *Selector {
	s.joins = append(s.joins, join{
		kind:  "JOIN",
		table: t,
	})
···
}
```
Will other JOIN kind like LEFT JOIN be supported in future?

**Comment by a8m** [comment]
JOIN is an internal detail of the sql storage driver for querying edges. What API are you looking for?

**Comment by leetesla** [comment]
#### such as:
```
func (s *Selector) LeftJoin(t TableView) *Selector {
	s.joins = append(s.joins, join{
		kind:  "LEFT JOIN",
		table: t,
	})
···
}
```
I'm looking for an API to build a SQL like :
`SELECT u.* FROM user u LEFT JOIN car c ON u.id=c.user_id WHERE u.name="lara"`

**Comment by a8m** [comment]
The SQL builders are used by the **generated code** to build queries (we built this DSL-like for SQL in order to generate the SQL query in one place, and avoid using strings everywhere in the generated code). 

When a developer uses an API like this: 
```go
groups, err := user.QueryGroups().All()
```
The SQL driver executes a query with JOIN in order get all user's groups. However, SQL terms (like JOIN) are not exposed to the developer (only when using custom predicates). 

The framework doesn't use or need other JOINs for querying edges. So, I don't see any reason for adding this. 

Are you using the SQL builders without using `entc`? Just as a standalone package?
