### ISSUE TITLE
entc generate fails with `undefined: field.TypeUUID`

### ISSUE THREAD

**Issue by lfaoro** [facebookincubator/ent#208]
Hi guys, I don't understand what I'm doing wrong, I don't have any `field.TypeUUID` in my schema

```shell
$ entc generate ./ent/schema
entc/load: # command-line-arguments
./entc_github.com_lfaoro_spark_ent_schema_1575076841.go:130:21: undefined: field.TypeUUID
```

I have a pretty simple schema, and I'm unable to debug this. Could you point me in the right direction?

```go
// Card holds the schema definition for the Card entity.
type Card struct {
	ent.Schema
}

// Fields of the Card.
func (Card) Fields() []ent.Field {
	return []ent.Field{
		field.String("user_id"),
		field.Bytes("ciphered_card"),

		field.String("token"),
		field.String("hash").Unique(),
		field.String("request_ip"),
		field.String("user_agent"),
		field.Time("expires_on"),
		field.Time("auto_delete_on"),
		field.Uint32("first_six"),
		field.Uint32("last_four"),
	}
}

// Edges of the Card.
func (Card) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("metadata", Metadata.Type).
			Unique(),

	}
}
```

**Comment by a8m** [comment]
I'm pretty sure you're facing the same problem as #191.

Please try to follow this [guide](https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent), and let me know if it does fix your problem.

**Comment by lfaoro** [comment]
Thank  you @a8m, indeed fixing package/tool versioning solved the issue.

I wonder about the complexity of adding such a check in the entc CLI, in order to notify users about package/tool version mismatch and point to the guide.

WDYT?

**Comment by a8m** [comment]
I was thinking actually to just use Go modules for this. Basically, generate for the user a file named `generate.go` that hold the command, and ask them to run `go generate`. 

Then, once you use `go run github.com/facebookincubator/ent/cmd/entc` inside your project directory, Go will use the package version that resides in your `go.mod` file and not GOPATH. 
The `generate.go` mentioned above, will use `go run ...` instead of the `entc` binary. See [this example](https://github.com/facebookincubator/ent/blob/master/examples/start/ent/generate.go#L7) (ignore the `--header` option). 

It's actually a common problem in frameworks that provide both CLI and a runtime package (e.g. go-swagger, gqlgen). 

WDYT?

**Comment by lfaoro** [comment]
I would avoid forcing people to use `go generate`. 

We could add a check in entc: check go.mod file, check internal version -- output warning on mismatch.

WDYT?

**Comment by a8m** [comment]
Yeah, sounds good. We can use [`debug.BuildInfo`](https://golang.org/pkg/runtime/debug/#BuildInfo) for this. 

I've opened an issue (https://github.com/golang/go/issues/35921) in Go repo about adding module support to `go/packages`. Let's wait a few days to see what goes with it. If it won't be accepted, I'll add this code by myself. 

Thanks.

**Comment by lfaoro** [comment]
You're very welcome @a8m
