### ISSUE TITLE
question: performance

### ISSUE THREAD

**Issue by aakhan1** [facebookincubator/ent#279]
Do you have any performance benchmarks published on this framework?

**Comment by a8m** [comment]
Hey, we actually ran some benchmark tests and compared `ent` with other frameworks before started working with it and the numbers were good. However, I decided to not publish them, because this project is in development and we should wait with it until v1. 

If you're looking for external benchmark, so [Vincent Blanchon](https://medium.com/@blanchon.vincent) wrote a [post about ent](https://medium.com/a-journey-with-go/go-ent-graph-based-orm-by-facebook-d9ba6d2290c6) and mentioned the results of the benchmark he did there. 

Thanks
