### ISSUE TITLE
Feature request: specify fields to select

### ISSUE THREAD

**Issue by ernado** [facebookincubator/ent#332]
We can limit field set we are selecting from database to allow optimizations (e.g. index-only SELECT)

Also would be interesting to integrate this with graphql later.
Not sure about API tho, let's discuss?

**Comment by a8m** [comment]
> We can limit field set we are selecting from database to allow optimizations (e.g. index-only SELECT)
>
> Also would be interesting to integrate this with graphql later.


There is an option for query specific fields, but it's not good enough as we wanted it to be:
```go
names, err := client.Pet.
    Query().
    Select(pet.FieldName).
    Strings(ctx)
```
We already started to work on GraphQL integration, and we plan to tackle this issue as well. I hope to OSS some of it in the near future (in a separate repo). 

If you think there are additional stuff to discuss here, keep the issue open. Otherwise, let’s close it.

**Comment by ernado** [comment]
Great, thank you! Let's close it for now.

**Comment by dilipkk-foyernet** [comment]
@a8m is this integrated with entgql?
