### ISSUE TITLE
generated code be friendly with staticcheck

### ISSUE THREAD

**Issue by nqd** [facebookincubator/ent#405]
Hi gents,

At first, thanks for the beautiful work.

Our CI is running staticcheck (which I believe ent is using also) and it returns this error

```{shell}
ent/privacy/privacy.go:16:2: error var Allow should have name of the form ErrFoo (ST1012)
ent/privacy/privacy.go:20:2: error var Deny should have name of the form ErrFoo (ST1012)
ent/privacy/privacy.go:24:2: error var Skip should have name of the form ErrFoo (ST1012)
```

Could you make those errors meet ST1012 req?

Many thanks,

**Comment by a8m** [comment]
Hey @nqd and thanks for raising up this issue. 

We actually found it nicer to use `privacy.Deny` rather than `privacy.ErrDeny` - I know that this is the [Go convention](https://github.com/golang/go/wiki/Errors#naming) for error names, but sometimes the `Err` prefix is redundant (e.g. `io.EOF`). 

Note that although the privacy directory is generated by `entc`, it's considered alpha (not documented yet), and may change in the upcoming weeks. These error names, might change as well. 

Either way, I don't think it's a bug, and I suggest to ignore generated files in linters - some linters, like `gocyclo` and `dupl` can fail as well. 

cc @alexsn
