### ISSUE TITLE
how to add a column in table which generated by M2M?

### ISSUE THREAD

**Issue by RiskyFeryansyahP** [facebookincubator/ent#438]
Hello, I have a problem when i using Many to Many(M2M) edges, the default generated table an column when im using M2M is only depend on what schema is related.

Example : 

Table users
- id
- username
- password

Table groups
- id
- group name
- etc

The result of generated table and column for that M2M table is :

Table users_group
- user_id
- group_id

nah, The problem is how to add custom column in generated table result M2M ?

Thanks before,

**Comment by a8m** [comment]
Hey @RiskyFeryansyahP and thanks for opening this issue.
It's not possible to add metadata on edges using ent at the moment, but it's on our [roadmap](https://github.com/facebookincubator/ent/issues/46) and should be addressed. 

Having said that, you can always do it manually by changing the generated table in the `migrate/schema` package (I'm not sure what you'll get for it, because you can't query/mutate these columns).

I'll open a separate issue for design discussion when we'll get to it. Closing

**Comment by RiskyFeryansyahP** [comment]
ahh i see @a8m, Thanks for the answering my question 😃

**Comment by alex9968** [comment]
when the problem could be  resolved
