### ISSUE TITLE
Question: Neptune / Gremlin - experience compared to SQL backends

### ISSUE THREAD

**Issue by kkom** [facebookincubator/ent#452]
Hey!

Firstly, thanks a ton for open sourcing this! As an ex-Facebooker I've been looking for a good privacy-aware ORM and seeing something based on the principles I'm already familiar with is fantastic! :)

I have some questions to the team about your experience using AWS Neptune.

I started using it, as my data model is highly connected and I think that it might benefit from efficient traversals across many hops. Things that otherwise would be very heavy SQL joins or even results of multiple queries stitched together in the API layer. I also like the idea of being able to hand craft complex traversals using Gremlin - same reason. These are all just hypotheses though.

Some questions, if you don't mind sharing your experience:

1) Is the lack of indexing a big problem for performance?
2) I see that migrations are not implemented either. Are we talking data migrations here? I thought Neptune is schema-less.
3) On 1-2: what priority is Gremlin for the team? Are you actually using this backend in your internal products, or is support a nice to have now? I.e. is it likely that support would become worse and worse with time, up until deprecation?
4) What about aggregations? Is the performance on par with SQL or better/worse?

So far it's just negatives, so here's a key question about potential upside:

5) Are there situations where it is beneficial to use Gremlin / Neptune? I'm thinking deep traversals that can be implemented as a single Gremlin query. Do those happen or rather no?

Any other thoughts or observations would be greatly appreciated too!

Thanks again and keep the good work going!

Best,
Konrad

**Comment by kkom** [comment]
Another upside for me is being able to easily export the entire graph into Spark GraphFrames/Graphx or some of the non-distributed graph processing frameworks (might have that need to run some algorithms). But that's a batch processing question, rather than realtime querying consideration, so probably not related to Ent very much.

**Comment by a8m** [comment]
Hey @kkom and thanks for the kind words.

I already answered here in a few issues about why we decided to switch from Neptune to MySQL - you're welcome to search it, because I don't really remember all the details, and **things might changed in Neptune since then**. 

> Is the lack of indexing a big problem for performance?

Not performance. The ability to define unique constraints on fields/edges or a combination of fields and edges. I found a [workaround](https://www.reddit.com/r/aws/comments/b7o4b6/neptune_how_do_i_add_a_unique_constraint_on) for this, but it's not ideal and we wanted the database to enforce that.

> I see that migrations are not implemented either. Are we talking data migrations here? I thought Neptune is schema-less.

Schema migration. We prefer typed-schema and again, we like the idea that the database enforce the data consistency. The missing option of reading the schema information led to many "surprises" at runtime and our users (ent users) didn't like that.

> On 1-2: what priority is Gremlin for the team? Are you actually using this backend in your internal products, or is support a nice to have now? I.e. is it likely that support would become worse and worse with time, up until deprecation?

No priority. However, I have some plans (after V1) to make the storage-backend pluggable and help users with integrations (dragph, Gremlin and others). 

> What about aggregations? Is the performance on par with SQL or better/worse?

Sorry, I don't really remember. But like I mentioned here in other issues, SQL worked better for us in all meanings. 


> Any other thoughts or observations would be greatly appreciated too!

Other stuff that I remember: 
- Neptune didn't support multi-tenancy (like named databases in MySQL) and it wasn't cost-effective and efficient to deploy a cluster (with replicas and backups) for each tenant. Deploying all tenants on the same graph and manage the sub-graphs virtually wasn't "secure and safe" enough for us.
- Neptune didn't support manual transactions. Think about case, where you use GraphQL and you want to wrap each mutation handler in a transaction. Then, run multiples ent-mutations on the database and when the mutation handler exits, you decide whether to commit or rollback.  
- Gremlin query language is alien to most engineers and the learning curve was much high then we thought. It's true that 99% of the time people use ent.Client, but sometimes (like debugging issues) people want to connect to the database and play with it.
- The Gremlin version of Neptune is not identical to the TinkerPop version.

Having said all that, I want to say that overall, Neptune is a great product of AWS and its team is very responsive and willing to help with every request or question, it just didn't work for our needs. 

Closing, but you can feel free to ping me on Twitter if you want to discuss

**Comment by kkom** [comment]
Thanks @a8m, super clear!
