### ISSUE TITLE
Panic during generation

### ISSUE THREAD

**Issue by erikh** [facebookincubator/ent#474]
Is there a way to force a stack trace on panic for `entc`? I'd love to debug this further.

https://github.com/erikh/ent-bug -- this schema panics the entc generator. To repro:

```
$ go run github.com/facebookincubator/ent/cmd/entc generate ./schema 
```

Which will fetch the appropriate version I was testing against, which is current master as of this posting (so if this gets fixed later, you know it's fixed).

Hope it's useful, but I don't know why it's happening yet. I'll post more as I discover.

**Comment by a8m** [comment]
Hey @erikh and thanks for reporting this. 
Checking this.

**Comment by erikh** [comment]
It's an old schema -- from back when I was working on the sqlite stuff. I also tried to thin it out some so you'll see some empty stuff in there... I think the problem is the edges between run and task, but still playing.

**Comment by a8m** [comment]
Found the issue. You should replace `ent.Mixin` in your mixins with `mixin.Schema`.

I posted about it in the release note - https://github.com/facebookincubator/ent/releases/tag/v0.2.0

I really try to avoid non-backwards compatible changes even before V1 (this was the first one), but we needed it in order to add support for other functionalities in mixin.

I'll leave this issue open for now and close it after I'll add more context to this kind of failures. 
Thanks and sorry

**Comment by erikh** [comment]
I missed it, I did just figure out it was the mixins. Thanks for the help debugging!

Also btw, the package name when you successfully generate -- is `ent-bug` due to an oversight by me; but it exposes another bug in the package name generation (go names can't have - in them). I'll report it separately if you'd like.

**Comment by a8m** [comment]
> Also btw, the package name when you successfully generate -- is ent-bug due to an oversight by me; but it exposes another bug in the package name generation (go names can't have - in them).

Good catch! 

>  I'll report it separately if you'd like.

No need, I'm on it.

What do you think we should do in this case, fail or just use "ent" as a package name?

**Comment by erikh** [comment]
I was thinking an underscore might be best here, and let go and the user
sort the rest out.
