### ISSUE TITLE
Missing best practices

### ISSUE THREAD

**Issue by sohaha** [facebookincubator/ent#501]
This package is cool and easy to use.

It seems that it is not very friendly to developers who traditionally use relational databases.

For example, a lot of things are processed internally,

but the document does not have information about performance optimization.

For example, `c.Users.WithGroups().Only(ctx)` seems to be unable to specify the field of group,

Will a large number of such queries affect performance?

**Comment by a8m** [comment]
Hey @sohaha,

> For example, c.Users.WithGroups().Only(ctx) seems to be unable to specify the field of group,

I'm not sure I understand what is the "field of the group". Do you mean to add a predicate on a specific group field? 

> Will a large number of such queries affect performance?

You can control the amount of entities that are returned using `.Where`, or `.Limit`. See the 2nd section in the [eager-loading page](https://entgo.io/docs/eager-load/#overview) - in order to see the queries that are executed (when you debug), use `c.Debug().User.Only(ctx)`, or use [opencensus tracing](https://entgo.io/docs/sql-integration/#use-opencensus-with-mysql).

If you want to add a new Wiki page in this repository (for best practices), you're welcome to open an issue with its content and we'll add it. 

Closing this issue, but feel free to open it or a different one for the Wiki page if you think it's needed. Thanks!

**Comment by sohaha** [comment]
.WithGroups(func (q Query){
// valid
q.Limit()
// can not achieve
q.Select("title")
}).All(ctx)

**Comment by sohaha** [comment]
@a8m Thank you for your reply. Please close it first. I haven't thought of the best practice yet.
