### ISSUE TITLE
Interface for Create/Update functions

### ISSUE THREAD

**Issue by chris-rock** [facebookincubator/ent#529]
Ent already generates similar functions for Create/Update functions. If you have to write a bit more complex code to handle create and update scenarios you'll end up writing a create and update function for ent, even though the logic may be similar. Consider the following example:

create a new one:

```
a8m, err := client.User.    // UserClient.
    Create().               // User create builder.
    SetName("a8m").         // Set field value.
    SetAge(30).    // Avoid nil checks.
    Save(ctx)               // Create and return.
```

handle existing entry:

```
a8m, err = a8m.Update().    // User update builder.
    SetName("a8m").         // Set field value.
    SetAge(31).             // Set field value
    Save(ctx)               // Save and return.
```

If ent would generate an interface for functions we could write the following:

```
entry, err := client.User.Create()
// gather existing
entry, err :=  a8m.Update()

entry.SetName("a8m"). 
SetAge(30). 
Save(ctx) 
```

At this point those interfaces can't be manually created since the return object for the methods is not an interface. Are there any other options that I missed?

**Comment by a8m** [comment]
Hey @chris-rock, I know exactly what you're talking about, because we encountered this issue when we started the development of ent, and because of the chaining API of the builders, you can't create a shared-interface because the return value is different (`interface<T>` would have solve this problem :/).

However, all type builders share the same [Mutation](https://entgo.io/docs/hooks/#mutation) type, and you can use the same mutation object for calling `SetName` on both create and update operations.

I'm not sure there's an API for getting the mutation object (except using custom template), so let me know if it does solve your issue and we can add it to the different builders.

**Comment by chris-rock** [comment]
I see, I missed the mutation object. Do you think it would be an option to expose the current mutation object like:

```
mutation := client.User.Create().Mutation()
mutation := client.User.Update().Mutation()
```

Since it will be explicit, its also clear that this mode will have no chaining.

**Comment by a8m** [comment]
Yes, we can add `Mutation() <T>Mutation` for the Create/Update/UpdateOne builders. 

Let me know if you want to add it, or I can do it later today.

**Comment by chris-rock** [comment]
@a8m Thank you for the quick feedback. If you find time to add this feature, I would very much appreciate it. If not, I'll try to add this capability this or next week.

**Comment by chris-rock** [comment]
Thank you for the quick turnaround @a8m! You make working with this project a pleasure!
