### ISSUE TITLE
Q: why SQL?

### ISSUE THREAD

**Issue by nonpcnpc** [facebookincubator/ent#54]
This looks _quite_ interesting. I have been recently looking into graph db due to the needs of my current project. I ended up with Dgraph but I struggled to work with its API and their horrendous documentation so I abandoned it altogether and came up with a custom in-memory solution(I only truly needed edges so it worked out).

Anyhow, this project looks like it would be perfect api layer on top of something like dgraph or underlying kvdb(badger, bolt) that abstracts the complexity away from the developer.

RDBMS was really not made for graphs, hence I wonder why SQL as a starting point for this type of project?

**Comment by a8m** [comment]
Thanks for raising this issue @nonpcnpc.
Actually, this project was developed initially on top of [Gremlin](gremlin), the graph traversal language used by Neo4j, AWS Neptune (and more), and extended to support SQL-based dialects in a later stage.

Right now, you can run `ent` on both graph-based and RDBMS databases. AFAIK, dgraph still doesn't not support Gremlin, but a storage driver for it can be implemented.

I have a WIP blog post that I plan to share about the switching from graph-based database to MySQL. Main reason were: missing features, sub-graph isolation, developers productivity and better performance. 

> RDBMS was really not made for graphs...

For developers, it doesn't matter (as long as the performance stays reasonable), because `ent` gives them the abstraction on top of their storage layer. However, BFS and DFS like traversals won't be supported.

You're welcome to see our [examples] and let me know what do you think. 

[gremlin]: https://en.wikipedia.org/wiki/Gremlin_(programming_language)
[examples]: https://github.com/facebookincubator/ent/tree/master/examples

**Comment by nonpcnpc** [comment]
Thanks for the info.

> and better performance

So the SQL backend can perform at the same level as dedicated graph db(neo4j...), or did you mean something else by that?

**Comment by a8m** [comment]
Yes. The performance tests we ran on our data-model showed better numbers.
But again, we didn't test dedicate graph database features (like shortest path).

I'll try to remember to update this issue when publishing the blog post.

**Comment by taliptako** [comment]
@a8m How this can be possible ?
[https://neo4j.com/news/how-much-faster-is-a-graph-database-really/](https://neo4j.com/news/how-much-faster-is-a-graph-database-really/)

**Comment by a8m** [comment]
Like I mentioned above, the benchmark tests we ran on our data-model between RDS and Neptune showed better result for RDS (some of them had traversals with depth 5). 

We didn't benchmark Neo4j and didn't compare all possible queries, but I feel that our data-model and the tests we ran cover the majority of the cases.

BTW, even the most complicated queries we compared (depth=5) were below 3 seconds.

**Comment by taliptako** [comment]
@a8m That's strange can I make some tests with your data too is it something you can share?

**Comment by a8m** [comment]
>  can I make some tests with your data too is it something you can share?

Not really, but you are welcome do run your own comparison and share with us the result.

Thanks!

**Comment by a8m** [comment]
Hey @taliptako - just wanted to update that I went over the example in "Neo4j in Action" (mentioned in the link you've added), and I don't have any doubt that graph databases perform better in these cases. 

However, queries like `user->friends->...->friends` on large datasets don't exist in our platform. When a query with long or complex computation needs to be applied, it usually runs in a different platform.

**Comment by taliptako** [comment]
I wonder if it's healthy to use this (ORM or OGM?) for such a query which needs a lot of join on large dataset? Is it capable to create right Gremlin queries under the hood
