### ISSUE TITLE
o2o-recursive storage key for edge is kind of confusing

### ISSUE THREAD

**Issue by kidlj** [facebookincubator/ent#548]
Per the o2o-recursive [example](https://entgo.io/docs/schema-edges/#o2o-same-type), `node_nex`t in db table actually means `node_prev`.

```
id	value	node_next
2	2	1
3	3	2
4	4	3
5	5	4
1	1	5
```

This change is introduced in #286.

**Comment by a8m** [comment]
Hey @kidlj,
I understand the confusion, but as mentioned in #285, we can't rely on inverse edges (`edge.From`) for naming the foreign-key columns, because they are optional and users can always drop them (#286 actually fixed a real bug we found in production).

However, I'm going to land #545 later today (or tomorrow), which give users the freedom to name foreign-key columns however they want.

**Comment by kidlj** [comment]
Even with custom edge storage key, this case is still anti-intuition, like ‘next’ edge must have a customized ‘prev_id’ storage key. 

When any edge changes, no matter a to edge or from edge added or dropped, auto migration should take care of the table structure and data migration, so use from edge as the storage key should not be a problem. 

If my understanding is not true, can you share more details about your production bug that this change has fixed? Thanks.

**Comment by a8m** [comment]
> If my understanding is not true, can you share more details about your production bug that this change has fixed? Thanks.

Sure, the inverse-edge (`edge.From`) was dropped (after a few months) and the storage-key was renamed (let's say, from `prev_id` to something else). Like I mentioned above, we can't rely on inverse-edge to set the storage-key name, because they are optional, and we try to stay consistent (unrelated to the bug mentioned above).

I'll try to give another example - let's say a user created a schema with a O2M relations (user->pets), and the inverse-edge was called "owner", in this scenario the storage-key would be called "owner_id", but if the same schema was defined without the inverse-edge, the storage-key was different (inferred from the `edge.To`). I don't like this inconsistency (unrelated to the bug mentioned above).  

Usually, ent users don't care about the storage-key names (because they use ent), and if they are, they can always use the `StorageKey` option.

> When any edge changes, no matter a to edge or from edge added or dropped, auto migration should take care of the table structure and data migration, so use from edge as the storage key should not be a problem.

Right, but the codegen doesn't support that, and that's one of the reasons we decided to integrate the migration logic with entc (ent codegen) in the near future. This one can be changed as well (support codegen and schema versions, history, etc).

Thanks for the great feedback.
