### ISSUE TITLE
Docs clarification: when are hooks called?

### ISSUE THREAD

**Issue by kkom** [facebookincubator/ent#553]
Hey!

I'm looking at https://entgo.io/docs/hooks/ where it says:

> The Hooks option allows adding custom logic before and after operations that mutate the graph.

Would it be possible to clarify this a bit?

1. Are the hooks called before or after the privacy layer?

2. Are they called before or after the mutation is committed to the DB?

3. The docs say "before and after operations" but I don't see the option to choose whether it happens before or after a mutation. Is the latter achieved through the use `defer`? And if so, is it possible to cancel the execution of a hook if mutation gets somehow cancelled?

My use case is synchronising the state of some ents to an external service, obviously only if the mutation succeeds. (That's why I would also like to have retries in my hook for extra reliability, but I suppose this can be done by hand).

Thanks in advance for any clarification! :)

Best,
Konrad

**Comment by a8m** [comment]
Hey Konrad,

> Are the hooks called before or after the privacy layer?

Privacy is not mentioned in the docs, because it's not official yet. The evaluation order for multiple hooks is described here: https://entgo.io/docs/hooks/#evaluation-order

> Are they called before or after the mutation is committed to the DB?

As mentioned in the docs, hooks are similar to the common HTTP middleware pattern. At the end, user's hooks wrap the last `ent.Mutator` which writes the data to the database.

```go
client.Use(func(next ent.Mutator) ent.Mutator {
    return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
        // code before.
        v, err := next.Mutate(ctx, m) // invoke the rest of the chain, and write to the database.
        // code after.
        return v, err
    })
})
```

> And if so, is it possible to cancel the execution of a hook if mutation gets somehow cancelled?

Use `context.Context` to propagate cancellation. 

More hooks examples can be found in the [integration tests](https://github.com/facebookincubator/ent/blob/master/entc/integration/hooks/hooks_test.go).

If you think that something specific is missing in the docs, you're welcome to add it or to propose it in an issue and we'll consider to add it. Thanks!

**Comment by kkom** [comment]
Thank you @a8m! If something concrete comes to my mind, I'll put up a PR on the docs!
