### ISSUE TITLE
ci: using goreleaser github-actions to add binaries to a tag/release

### ISSUE THREAD

**Issue by paulvollmer** [facebookincubator/ent#591]
the goreleaser github-action is great to automate the build and upload of build artifacts if a new git tag was created.

at the moment no binaries are available at the release pages and by adding a `.goreleaser` config and a github-actions workflow this can be automated.

Let me know if you like the idea and i can send a PR for that.

**Comment by a8m** [comment]
Hey @paulvollmer and thanks for proposing this.

I'm not sure if we want/need this for 2 reasons:
1. entc is not a standalone binary and requires Go and ent (as a dependency).
2. entc is optional in the first installation (e.g. `entc init`), and we ask users to use `go generate` (and not entc directly) in order to keep version compatibility between ent and entc using Go modules (see [docs](https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent)).

**Comment by paulvollmer** [comment]
okay, i missed the docs page you mentioned. i had in mind that it is good to have the possibility to download an earlier version of entc without checking out a specific git tag. i'll close the issue now.
