### ISSUE TITLE
Feature: raw query representation

### ISSUE THREAD

**Issue by christie-zhao** [facebookincubator/ent#667]
Is there a way we can turn the query to the raw SQL format? For example: 
Like a method like `Manager.raw()` which turns this
```
users, err := client.User.      // UserClient.
    Query().                    // User query builder.
    Where(user.HasFollowers()). // filter only users with followers.
    All(ctx)                    // query and return.
```

to `SELECT * FROM User WHERE hasFollowers != false`
I am trying to add more feature like `Create Materialized View` to my ent project but it is hard to communicate raw query with the API. Are there any suggestions?

**Comment by a8m** [comment]
Hey @christie-zhao!
If want to see the outgoing query use `client.Debug()` to get a debug client, or create your own [`dialect.Driver`](https://godoc.org/github.com/facebookincubator/ent/dialect#Driver) (see an [example](https://github.com/facebookincubator/ent/blob/1e10f4f/dialect/dialect.go#L73) how to wrap an existing driver).

If you want to get the actual query (with its parameters), you'll need to use [external-templates](https://entgo.io/docs/templates/) to generate this API since we don't expose this functionality (see the `<Node>Query.querySpec()` method).

**Comment by a8m** [comment]
Closing, but feel free to continue the discussion and ask questions if you need help with that.

**Comment by christie-zhao** [comment]
Thanks! I do have a question. I want to add Select().From() feature in `query` but currently it is not supported. It only supports `sql.Select().From()`. Is it possible to make them interact?
